### ISSUE TITLE
on the new join send each enemy's health

### ISSUE THREAD

**Issue by randallwc** [ECE-180D-WS-2022/Team3#162]
so if you are the host
then you damage an enemy before anyone else joins
then someone else joins
and they damage that enemy
then that enemy is broken and if anyone attacks it they get a key error

**Comment by randallwc** [comment]
```
Traceback (most recent call last):
  File "/Users/william/GitHub/Team3/client/main.py", line 5, in <module>
    game.run()
  File "/Users/william/GitHub/Team3/client/Game.py", line 674, in run
    self.play()
  File "/Users/william/GitHub/Team3/client/Game.py", line 594, in play
    self._display_enemies()
  File "/Users/william/GitHub/Team3/client/Game.py", line 390, in _display_enemies
    if enemy.type in enemy.bad_enemies:
AttributeError: 'Enemy' object has no attribute 'type'
```
