### ISSUE TITLE
key error in multiplayer which is different than on join key error

### ISSUE THREAD

**Issue by randallwc** [ECE-180D-WS-2022/Team3#172]
```
pygame 2.1.2 (SDL 2.0.18, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
test.mosquitto.org team3/controller/name
['LG QHD', 'MacBook Pro Microphone', 'MacBook Pro Speakers', 'ZoomAudioDevice']
Connected to: https://skydangerranger.herokuapp.com/
Server:  Welcome to sky danger ranger! we're glad to have you here. It's gonna be a ride!
Socket ID:  wrf91EVZn5uGdDZiAAAP
Traceback (most recent call last):
  File "/Users/william/GitHub/Team3/client/main.py", line 5, in <module>
    game.run()
  File "/Users/william/GitHub/Team3/client/game.py", line 733, in run
    self.play()
  File "/Users/william/GitHub/Team3/client/game.py", line 635, in play
    self._display_enemies()
  File "/Users/william/GitHub/Team3/client/game.py", line 438, in _display_enemies
    self.server.remove_enemy_from_server(enemy.id)
  File "/Users/william/GitHub/Team3/client/server_iface.py", line 175, in remove_enemy_from_server
    self.socket.emit('remove_enemy', {"id": enemy_id})
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/socketio/client.py", line 393, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
```

**Comment by jcr7467** [comment]
This is just when socket disconnects. closing
